### ISSUE TITLE
bot api types

### ISSUE THREAD

**Issue by timoniq** [timoniq/telegrinder#59]
telegrinder uses schema at https://github.com/ark0f/tg-bot-api to generate types. its super old and not getting updates :c 
probably new schema must be applied and \*unfortunately\* most likely type generator will have to be revised for the found new schema specifications

**Comment by luwqz1** [comment]
> telegrinder uses schema at https://github.com/ark0f/tg-bot-api to generate types. its super old and not getting updates :c probably new schema must be applied and *unfortunately* most likely type generator will have to be revised for the found new schema specifications

btw i havent found a single scheme that have full information about enumerations. Therefore there is a proposal that contributors can create enumerations for example in yaml configs.

for example, enumeration ChatMemberStatus:

```yaml
enum_name: "ChatMemberStatus"
enumerations:
    - administrator
    - banned
    - left
    - member
    - owner
    - restricted
uses:
    - ChatMember.status
```

I think we need to think more about the syntax for creating enumerations...
