### ISSUE TITLE
typechecking 'strict' mode

### ISSUE THREAD

**Issue by luwqz1** [timoniq/telegrinder#60]
to improve typing guarantees, it is suggested to set the 'strict' mode for pyright. it is expected that there are over a thousand type errors. it will take some time to fix them

```toml
[tool.pyright]
typeCheckingMode = "strict"
```
